import './globals.css'
import { Inter } from 'next/font/google'
import NavBar from './../components/NavBar';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Helitha Sri Portfolio',
  description: 'Generated by create next app',
  icons: {
    icon: './favicon.ico',
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="w-full h-screen bg-bodyColor overflow-x-hidden overflow-y-scroll">
        <NavBar/>
        {children}
      </body>
    </html>
  )
}
